name: Check Style
on: push

jobs:
  check-style:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: Install tools
        run: python3 -m pip install --upgrade pip pycodestyle

      - name: Check Style
        run: pycodestyle --first *.py
                        
      - name: Test with unittest
        run: python3 -m unittest tests/test.py
          
      - name: Check code coverage                        
        run:
          python3 -m coverage run -m unittest tests/test.py
          python3 -m coverage report
          python3 -m coverage html
          
      - name: Archive code coverage HTML report
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: htmlcov